spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
      routes:
        - id: academic-server
          uri: ${SPECIALIZATION_SERVER_URL:http://localhost:8082}/
          predicates:
            - Path=/api/specializations/**, /api/disciplines/**, /api/tags/**, /api/curriculums/**
        - id: security-server
          uri: ${SECURITY_SERVER_URL:http://localhost:8081}/
          predicates:
            - Path=/api/security/**, /api/users/**, /api/roles/**, /api/permissions/**

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway: INFO
