spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: specialization-server
          uri: ${SPECIALIZATION_SERVER_URL:http://localhost:8082}/
          predicates:
            - Path=/api/specializations/**
            - Path=/api/disciplines/**

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.cloud.gateway: INFO