version: "3.9"
services:
  security-server:
    container_name: security-server
    image: fenix23707/security-server:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-uis:5432/uis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8081:8080"
    depends_on:
      - postgres-uis

  specialization-server:
    container_name: specialization-server
    image: fenix23707/specialization-server:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-uis:5432/uis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8082:8080"
    depends_on:
      - postgres-uis

  postgres-uis:
    container_name: postgres-order
    image: postgres:15
    environment:
      POSTGRES_DB: uis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-uis:/data/postgres
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    expose:
      - "5432"
    ports:
      - "5431:5432"
    restart: always