spring:
  application:
    name: academic-server
server:
  port: 8080
uis:
  security-server-url: ${SECURITY_SERVER_URL:http://localhost:8081}
jwk-set-uri: ${uis.security-server-url}/api/internal/security/jwk-set-uri
