springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.auth: DEBUG

server:
  port: 8080

uis:
  security:
    admin-username: ${UIS_ADMIN_USERNAME:admin}
    admin-password: ${UIS_ADMIN_PASSWORD:admin}
    admin-role-name: ${UIS_ADMIN_PASSWORD:admin}
  claim-name:
      user-id: user_id


