spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver # TODO user real db
    username: root
    password: root
    h2:
      console:
        enable: true
        path: /h2
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql


mybatis:
  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    cache-enabled: true
#    default-statement-timeout: 3000
#    map-underscore-to-camel-case: true
#    use-generated-keys: true

#  type-handlers-package: io.spring.infrastructure.mybatis

logging:
  level:
    com:
      spring:
        ibatis: DEBUG

