spring:
  datasource:
#    url: jdbc:h2:mem:mydb
    driver-class-name: org.postgresql.Driver  # TODO user real db
#    username: root
#    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

#hibernate:
#  temp:
#    use_jdbc_metadata_defaults: true



