spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uis
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver  # TODO user real db
    username: postgres
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

#hibernate:
#  temp:
#    use_jdbc_metadata_defaults: true



