name: build-dependencies
on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build common libraries
        run: |
          cd common-libraries
          mvn clean install
          cd ..
