name: build-dependencies
on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build common libraries
        run: |
          cd common-libraries
          mvn clean install
          cd ..