# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci-pull-request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build common libraries
      run: |
        cd common-libraries
        mvn clean install
        cd ..

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Gateway Server Build and Push to DockerHub
      run: |
        cd gateway-server
        mvn clean install
        docker build -t fenix23707/gateway-server:dev .
        docker push fenix23707/gateway-server:dev
        cd ..

    - name: Security Server Build and Push to DockerHub
      run: |
        cd security-server
        mvn clean install
        docker build -t fenix23707/security-server:dev .
        docker push fenix23707/security-server:dev
        cd ..

    - name: Academic Server Build and Push to DockerHub
      run: |
        cd academic-server
        mvn clean install
        docker build -t fenix23707/academic-server:dev .
        docker push fenix23707/academic-server:dev
        cd ..
